eCom/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('jet/',include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls','jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    
]

main/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home,name='home'),
    path('search',views.search,name='search'),
    path('category-list',views.category_list,name='category-list'),
    path('brand-list',views.brand_list,name='brand-list'),
    path('product-list',views.product_list,name='product-list'),
    path('category-product-list/<int:cat_id>',views.category_product_list,name='category-product-list'),
    path('brand-product-list/<int:brand_id>',views.brand_product_list,name='brand-product-list'),
    path('product/<str:slug>/<int:id>',views.product_detail,name='product_detail'),
    path('filter-data',views.filter_data,name='filter_data'),
    path('load-more-data',views.load_more_data,name='load_more_data'),
    path('add-to-cart',views.add_to_cart,name='add-to-cart'),
    path('cart',views.cart_list,name='cart'),
    path('delete-from-cart',views.delete_cart_item,name='delete-from-cart'),
    path('update-cart',views.update_cart_item,name='update-cart'),
    path('accounts/signup',views.signup,name='signup'),
    path('checkout',views.checkout,name='checkout'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('save-review/<int:pid>',views.save_review, name='save-review'),
    




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/models.py
from distutils.command.upload import upload
import re
from tabnanny import verbose
from turtle import title
from unicodedata import category
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

# banner
class Banner(models.Model):
    img = models.ImageField(upload_to="banner_imgs/")
    alt_text = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural='1. Banners'

    def image_tag(self):
        return mark_safe('<img src="%s" width="100"  />' % (self.img.url))

    def __str__(self):
        return self.alt_text
# category
class Categories(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="cat_imgs/")
    
    class Meta:
        verbose_name_plural='2. Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

# brand
class Brand(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="brand_imgs/")

    class Meta:
        verbose_name_plural='3. Brands'

    def __str__(self):
        return self.title

# size
class Size(models.Model):
    title = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural='5. Sizes'

    def __str__(self):
        return self.title

# color
class Color(models.Model):
    title = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='4. Colors'

    def color_bg(self):
        return mark_safe('<div style="width:30px;height:30px; background-color:%s"></div>' % (self.color_code))

    def __str__(self):
        return self.title


# product
class Product(models.Model):
    title = models.CharField(max_length=200)

    slug = models.CharField(max_length=100)
    detail = models.TextField()
    specs = models.TextField()
    category=models.ForeignKey(Categories,on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    color = models.ForeignKey(Color,on_delete=models.CASCADE)
    size = models.ForeignKey(Size,on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    
    class Meta:
        verbose_name_plural='6. Products'
    

    def __str__(self):
        return self.title

# product attribute
class ProductAttribute(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    color = models.ForeignKey(Color,on_delete=models.CASCADE)
    size = models.ForeignKey(Size,on_delete=models.CASCADE)
    price = models.PositiveBigIntegerField()
    image = models.ImageField(upload_to="product_imgs/",null=True)
    
    class Meta:
        verbose_name_plural='7. ProductAttributes'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.product.title

# Order
class CartOrder(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    total_amt=models.FloatField()
    paid_status=models.BooleanField(default=False)
    order_dt=models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural='8. Orders'

# OrderItems
class CartOrderItems(models.Model):
    order=models.ForeignKey(CartOrder,on_delete=models.CASCADE)
    invoice_no=models.CharField(max_length=150)
    item=models.CharField(max_length=150)
    image=models.CharField(max_length=200)
    qty=models.IntegerField()
    price=models.FloatField()
    total=models.FloatField()

    class Meta:
        verbose_name_plural='9. Order Items'

    
    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />' % (self.image))

# Product Review
RATING=(
    (1,'1'),
    (2,'2'),
    (3,'3'),
    (4,'4'),
    (5,'5'),
)
class ProductReview(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    review_text=models.TextField()
    review_rating=models.CharField(choices=RATING,max_length=150)

    class Meta:
        verbose_name_plural='Reviews'

    def get_review_rating(self):
        return self.review_rating

   

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import ProductReview

class SignupForm(UserCreationForm):
    full_name=forms.CharField(max_length=50,required=True)
    mobile=forms.CharField(widget=forms.TextInput(attrs={'type':'number'}))
    address=forms.CharField(max_length=50,required=True)

    class Meta:
        model=User
        fields=('full_name','mobile','address','username','password1','password2')

# Review Add Form
class ReviewAdd(forms.ModelForm):
	class Meta:
		model=ProductReview
		fields=('review_text','review_rating')

main/views.py
from django.http import JsonResponse,HttpResponse
from django.db.models import Max,Min,Count,Avg
from django.shortcuts import render,redirect
from .models import *
from django.template.loader import render_to_string
from .forms import ReviewAdd, SignupForm
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
#paypal
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm


# home page
def home(request):
    banners=Banner.objects.all().order_by('-id')
    data=Product.objects.filter(is_featured=True).order_by('-id')
    return render(request,'index.html',{'data':data,'banners':banners})

# category
def category_list(request):
    data = Categories.objects.all().order_by('-id')
    return render(request,'category_list.html',{'data':data})

# brand
def brand_list(request):
    data=Brand.objects.all().order_by('-id')
    return render(request,'brand_list.html',{'data':data})

# product
def product_list(request):
    total_data=Product.objects.count()
    data=Product.objects.all().order_by('-id')[:3]
    min_price=ProductAttribute.objects.aggregate(Min('price'))
    max_price=ProductAttribute.objects.aggregate(Max('price'))
    return render(request,'product_list.html',
    {
        'data':data,
		'total_data':total_data,
		'min_price':min_price,
		'max_price':max_price,
        
        })

# product list according to category
def category_product_list(request,cat_id):
    category=Categories.objects.get(id=cat_id)
    data=Product.objects.filter(category=category).order_by('-id')
    return render(request,'category_product_list.html',{'data':data,})

# product list according to brand
def brand_product_list(request,brand_id):
    brand=Brand.objects.get(id=brand_id)
    data=Product.objects.filter(brand=brand).order_by('-id')
    return render(request,'category_product_list.html',{'data':data,})

# product detail
def product_detail(request,slug,id):
    product=Product.objects.get(id=id)

    # related products
    related_products=Product.objects.filter(category=product.category).exclude(id=id)[:4]


    colors=ProductAttribute.objects.filter(product=product).values('color__id','color__title','color__color_code').distinct()
    sizes=ProductAttribute.objects.filter(product=product).values('size__id','size__title','price','color__id').distinct()

    # review
    reviewForm=ReviewAdd()

	# Check
    canAdd=True
    reviewCheck=ProductReview.objects.filter(user=request.user,product=product).count()
    if request.user.is_authenticated:
        if reviewCheck > 0:
            canAdd=False
    #end
    
    #fetch reviews
    reviews=ProductReview.objects.filter(product=product)
    #end

	# Fetch avg rating for reviews
    avg_reviews=ProductReview.objects.filter(product=product).aggregate(avg_rating=Avg('review_rating'))
	# End

    return render(request, 'product_detail.html',{'data':product,'related':related_products,'colors':colors,'sizes':sizes,'reviewForm':reviewForm,'canAdd':canAdd,'reviews':reviews,'avg_reviews':avg_reviews})

# search
def search(request):
    q=request.GET['q']
    data=Product.objects.filter(title__icontains=q,).order_by('-id')
    return render(request,'search.html',{'data':data,})

# filter data
def filter_data(request):
    colors=request.GET.getlist('color[]')
    categories=request.GET.getlist('category[]')
    brands=request.GET.getlist('brand[]')
    sizes=request.GET.getlist('size[]')
    minPrice=request.GET['minPrice']
    maxPrice=request.GET['maxPrice']
    allProducts=Product.objects.all().order_by('-id').distinct()
    allProducts=allProducts.filter(productattribute__price__gte=minPrice)
    allProducts=allProducts.filter(productattribute__price__lte=maxPrice)
    if len(colors)>0:
        #searching color in productattribute section
        allProducts=allProducts.filter(productattribute__color__id__in=colors).distinct()
    if len(categories)>0:
        allProducts=allProducts.filter(category__id__in=categories).distinct()
    if len(brands)>0:
        allProducts=allProducts.filter(brand__id__in=brands).distinct()
    if len(sizes)>0:
        allProducts=allProducts.filter(productattribute__size__id__in=sizes).distinct()
    t=render_to_string('ajax/product-list.html',{'data':allProducts})
    return JsonResponse({'data':t})
    
# load more data
def load_more_data(request):
    offset=int(request.GET['offset'])
    limit=int(request.GET['limit'])
    total_data=Product.objects.count()
    data=Product.objects.all().order_by('-id')[offset:offset+limit]
    t=render_to_string('ajax/product-list.html',{'data':data})
    return JsonResponse({'data':t})

# Add to cart
def add_to_cart(request):
    
    cart_p={}
    cart_p[str(request.GET['id'])]={
        'image':request.GET['image'],
    	'title':request.GET['title'],
    	'qty':request.GET['qty'],
    	'price':request.GET['price']
    }
    if 'cartdata' in request.session:
        if str(request.GET['id']) in request .session['cartdata']:
            cart_data=request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty']=int(cart_p[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cartdata']=cart_data
        else:
            cart_data=request.session['cartdata']
            cart_data.update(cart_p)
            request.session['cartdata']=cart_data

    else:
        request.session['cartdata']=cart_p
    return JsonResponse({'data' : request.session['cartdata'],'totalitems':len(request.session['cartdata'])})

# cart list page
def cart_list(request):
    total_amt=0
    if 'cartdata' in request.session:
        for p_id,item in request.session['cartdata'].items():
            total_amt+=int(item['qty'])*float(item['price'])
        return render(request,'cart.html',{'cart_data' : request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt})
    return render(request,'cart.html')

# update cart item
def update_cart_item(request):
    p_id=str(request.GET['id'])
    p_qty=request.GET['qty']
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data=request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty']=p_qty
            request.session['cartdata']=cart_data
    total_amt=0
    for p_id,item in request.session['cartdata'].items():
        total_amt+=int(item['qty'])*float(item['price'])
    t=render_to_string('ajax/cart-list.html',{'cart_data' : request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt ,})
    return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})
    
# delete cart item
def delete_cart_item(request):
    p_id=str(request.GET['id'])
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data=request.session['cartdata']
            del request.session['cartdata'][p_id]
            request.session['cartdata']=cart_data
    total_amt=0
    for p_id,item in request.session['cartdata'].items():
        total_amt+=int(item['qty'])*float(item['price'])
    t=render_to_string('ajax/cart-list.html',{'cart_data' : request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt ,})
    return JsonResponse({'data':t,'totalitems':len(request.session['cartdata'])})

# Signup
def signup(request):
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            pwd=form.cleaned_data.get('password1')
            user=authenticate(username=username,password=pwd)
            login(request, user)
            return redirect('home')
    form=SignupForm
    return render(request, 'registration/signup.html',{'form':form})

# Checkout
@login_required
def checkout(request):
	total_amt=0
	totalAmt=0
	if 'cartdata' in request.session:
		for p_id,item in request.session['cartdata'].items():
			totalAmt+=int(item['qty'])*float(item['price'])
		# Order
		order=CartOrder.objects.create(
				user=request.user,
				total_amt=totalAmt
			)
		# End
		for p_id,item in request.session['cartdata'].items():
			total_amt+=int(item['qty'])*float(item['price'])
			# OrderItems
			items=CartOrderItems.objects.create(
				order=order,
				invoice_no='INV-'+str(order.id),
				item=item['title'],
				image=item['image'],
				qty=item['qty'],
				price=item['price'],
				total=float(item['qty'])*float(item['price'])
				)
			# End
		# Process Payment
		host = request.get_host()
		paypal_dict = {
		    'business': settings.PAYPAL_RECEIVER_EMAIL,
		    'amount': total_amt,
		    'item_name': 'OrderNo-'+str(order.id),
		    'invoice': 'INV-'+str(order.id),
		    'currency_code': 'USD',
		    'notify_url': 'http://{}{}'.format(host,reverse('paypal-ipn')),
		    'return_url': 'http://{}{}'.format(host,reverse('payment_done')),
		    'cancel_return': 'http://{}{}'.format(host,reverse('payment_cancelled')),
		}
		form = PayPalPaymentsForm(initial=paypal_dict)
		return render(request, 'checkout.html',{'cart_data':request.session['cartdata'],'totalitems':len(request.session['cartdata']),'total_amt':total_amt,'form':form})

@csrf_exempt
def payment_done(request):
	returnData=request.POST
	return render(request, 'payment-success.html',{'data':returnData})


@csrf_exempt
def payment_canceled(request):
	return render(request, 'payment-fail.html')

# Save Review
def save_review(request,pid):
	product=Product.objects.get(pk=pid)
	user=request.user
	review=ProductReview.objects.create(
		user=user,
		product=product,
		review_text=request.POST['review_text'],
		review_rating=request.POST['review_rating'],
		)
	data={
		'user':user.username,
		'review_text':request.POST['review_text'],
		'review_rating':request.POST['review_rating']
	}

main/templates/brand_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Brands</h3>
	<div class="row">
		{% if data %}
			{% for brand in data %}
			<div class="col-md-3 mb-4">
				<div class="card shadow">
				<a href="/brand-product-list/{{brand.id}}"><img src="{% static '/media/' %}{{brand.image}}" class="card-img-top" alt="{{brand.title}}" /></a>
				<div class="card-body">
					<h6 class="card-text"><a href="#">{{brand.title}}</a></h6>
				</div>
				</div>
			</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

main/templates/brand_product_list.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="{% static '/media/' %}{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
						<h6>Rs. {{product.productattribute_set.first.price}} </h6>
					  </div>
					  <div class="card-footer">
					  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
			
		</div>
	</div>
</main>
{% endblock %}

main/templates/category_list.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Categories</h3>
	<div class="row">
		{% if data %}
		{% for cat in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/category-product-list/{{cat.id}}"><img src="{% static '/media/' %}{{cat.image}}" class="card-img-top" alt="{{cat.title}}" /></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="#">{{cat.title}}</a></h6>
			  </div>
			</div>
		</div>
		{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

main/templates/category_product_list.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				
				{% for product in data %}
				<div class="col-md-4 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="{% static '/media/' %}{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					</div>
						<div class="card-footer">
						<input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
						<input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
						<input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
						<input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
						<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
			
		</div>
	</div>
</main>
{% endblock %}

main/templates/index.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {%  for banner in banners %}
    {% if forloop.counter == 1 %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
    {% else %}
    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
    {% endif %}
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {%  for banner in banners %}
    {% if forloop.counter == 1 %}
    <div class="carousel-item active">
      {% else %}
      <div class="carousel-item">
      {% endif %}
      <img src="{% static '/media/' %}{{banner.img}}" class="d-block w-100" style="height: 300px;width:1400px;" alt="...">
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">Featured Products</h3>
	<div class="row">
    {% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="{% static '/media/' %}{{product.productattribute_set.first.image}}" class="card-img-top" alt="..."></a>
			  <div class="card-body">
			    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
          <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
			  </div>
			  <div class="card-footer">
          
          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
			  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger " data-index="{{product.id}}"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
	<p class="my-4 text-center"><a href="{% url 'product-list' %}" class="btn btn-dark btn-sm">All Products <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

main/templates/payment-fail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4" id="cartList">
    <p>Payment Failed</p>
</main>
{% endblock %}

main/templates/payment-success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4" id="cartList">
    <p>Payment Success</p>
</main>
{% endblock %}

main/templates/product_list.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="{% static '/media/' %}{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="product-price-{{product.id}}">{{product.productattribute_set.first.price}}</span></h6>
					  </div>
					  	<div class="card-footer">
				          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
				          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
				          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
				          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
					  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
					  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="{{total_data}}" data-limit="3" class="btn btn-dark btn-sm">Load More <i class="fa fa-sync load-more-icon"></i></a></button>
		</div>
	</div>
</main>
{% endblock %}

main/templates/search.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}

<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1"><span class="text-muted">Search results for </span>{{request.GET.q}}</h3>
	<div class="row">
    {% for product in data %}
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="{% static '/media/' %}{{product.productattribute_set.first.image}}" class="card-img-top" alt="..."></a>
			  <div class="card-body">
			    <h6 class="card-text"><a href="/detail.php"></a></h6>
			  </div>
			  <div class="card-footer">
			  	<button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
			  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
	
</main>
{% endblock %}